# Generated by Django 6.0 on 2025-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('start_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('end_price', models.IntegerField()),
            ],
        ),
    ]
