# Generated by Django 6.0 on 2026-01-21 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_lot_image_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default='Auction Title', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
