# Generated by Django 6.0.1 on 2026-01-23 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='start_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
