# Generated by Django 6.0.1 on 2026-01-23 17:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_alter_lot_start_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='unknown')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='lots.lot')),
            ],
        ),
    ]
