# Generated by Django 6.0.1 on 2026-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_remove_bid_username_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_image/'),
        ),
    ]
